sudo: false

language: java

jdk: oraclejdk8

notifications:
  irc: "chat.freenode.net#seedstack-dev"

cache:
  directories: "$HOME/.m2/repository"

install: rm ~/.m2/settings.xml

script: mvn -q -U -T 2 -Psnapshots install
